baseurl = "http://example.com"
languageCode = "en-us"
title = "Shekhar Gulati Bookshelf"

[Params]
  Author = "Shekhar Gulati"
  disqusShortname = "shekhargulati"
  GoogleAnalyticsUserID = "UA-73784822-1"
